### PR TITLE
Add better button

### PR DESCRIPTION
**Pull request by JeanGuyTheJanitor**
I just make you an exemple in index.html but you should make it for all the sidebar : - )

### CODE REVIEW

**Comment by dinde451** [comment]
thanks chong, I has already plan to add it later (I'm working on the button desing) :-)

**Comment by JeanGuyTheJanitor** [comment]
: - )

**Comment by JeanGuyTheJanitor** [comment]
I'm am suprise to saw you make a website you tell on discord that you dont know a shit about code

**Comment by dinde451** [comment]
> I'm am suprise to saw you make a website you tell on discord that you dont know a shit about code

I'm shit with c# but in HTML I'm good, I work for a Marsmouche Studio (game creator)

**Comment by JeanGuyTheJanitor** [comment]
HO, TURKEY AND SQUIRREL... thats why you send me message on facebook for you diablo mod

**Comment by dinde451** [comment]
> HO, TURKEY AND SQUIRREL... thats why you send me message on facebook for you diablo mod

yes, I saw that you have played T&S a lot so i send you the link to diablo 1 devX and Theo's lair
(Your #1 on T&S)

**Comment by JeanGuyTheJanitor** [comment]
> > HO, TURKEY AND SQUIRREL... thats why you send me message on facebook for you diablo mod
> 
> yes, I saw that you have played T&S a lot so i send you the link to diablo 1 devX and Theo's lair (Your #1 on T&S)

I'm fucking level 12 on T&S... 12 hour... LOL

**Comment by dinde451** [comment]
> > > HO, TURKEY AND SQUIRREL... thats why you send me message on facebook for you diablo mod
> > 
> > 
> > yes, I saw that you have played T&S a lot so i send you the link to diablo 1 devX and Theo's lair (Your #1 on T&S)
> 
> I'm fucking level 12 on T&S... 12 hour... LOL

you levelup on a old master, if you put the same time on it now you will be lv24!!!

**Comment by JeanGuyTheJanitor** [comment]
holy shit!

**Comment by JeanGuyTheJanitor** [comment]
when is the season 2?

**Comment by dinde451** [comment]
ladder season 2 start in the end of august or maybe September

**Comment by JeanGuyTheJanitor** [comment]
ok, I'm relax I have already like 10 crown, i can buy new season for me and a freind LOL

**Comment by dinde451** [comment]
cool, i have to go now but have a nice day!

**Comment by JeanGuyTheJanitor** [comment]
yup, for sure. I am fan #1 of T&S, Freak's house, Theo's lair (a little less of warzibu (sorry but this game is not so good...))Your a fucking god, Your a fucking legend, your fucking Turkeydev1!

**Comment by dinde451** [comment]
> yup, for sure. I am fan #1 of T&S, Freak's house, Theo's lair (a little less of warzibu (sorry but this game is not so good...))Your a fucking god, Your a fucking legend, your fucking Turkeydev1!

Thanks bro, I create Marsmouche studio all these game are my baby :-)

**Comment by JeanGuyTheJanitor** [comment]
> > yup, for sure. I am fan #1 of T&S, Freak's house, Theo's lair (a little less of warzibu (sorry but this game is not so good...))Your a fucking god, Your a fucking legend, your fucking Turkeydev1!
> 
> Thanks bro, I create Marsmouche studio all these game are my baby :-)

yup, for sure have a good night : - )

**Pull request closed without merging**
